use airline_system;

Select DISTINCT f1.Flight_number as FirstFlightNumber, f2.Flight_number as SecondFlightNumber, f3.Flight_number as ThirdFlightNumber, f1.weekdays as firstweekday, f2.weekdays as secondweekday, f3.weekdays as thirdweekday, f1.Departure_airport_code as Origin,f1.Arrival_airport_code as FirstStop, f2.Arrival_airport_code as SecondStop , f3.Arrival_airport_code as Destination from FLIGHT as f1 join FLIGHT as f2 join FLIGHT as f3 on (f1.Arrival_airport_code=f2.Departure_airport_code AND f2.Arrival_airport_code=f3.Departure_airport_code) and timediff(f2.Scheduled_Departure_time,f1.Scheduled_arrival_time)>'01:00:00' and timediff(f3.Scheduled_Departure_time,f2.Scheduled_arrival_time)>'01:00:00' where f1.Departure_airport_code='OAK' AND f3.Arrival_airport_code='MIA' and ((f1.Weekdays NOT like '%Mon%' or f2.Weekdays like '%Mon%') and (f1.Weekdays NOT like '%Tue%' or f2.Weekdays like '%Tue%') and (f1.Weekdays NOT like '%Wed%' or f2.Weekdays like '%Wed%') and (f1.Weekdays NOT like '%Thu%' or f2.Weekdays like '%Thu%') and (f1.Weekdays NOT like '%Fri%' or f2.Weekdays like '%Fri%') and (f1.Weekdays NOT like '%Sat%' or f2.Weekdays like '%Sat%') and (f1.Weekdays NOT like '%Sun%' or f2.Weekdays like '%Sun%') and (f2.Weekdays NOT like '%Mon%' or f3.Weekdays like '%Mon%') and (f2.Weekdays NOT like '%Tue%' or f3.Weekdays like '%Tue%') and (f2.Weekdays NOT like '%Wed%' or f3.Weekdays like '%Wed%') and (f2.Weekdays NOT like '%Thu%' or f3.Weekdays like '%Thu%') and (f2.Weekdays NOT like '%Fri%' or f3.Weekdays like '%Fri%') and (f2.Weekdays NOT like '%Sat%' or f3.Weekdays like '%Sat%') and (f2.Weekdays NOT like '%Sun%' or f3.Weekdays like '%Sun%'));

Select DISTINCT f1.Flight_number as FirstFlightNumber, f2.Flight_number as SecondFlightNumber, f3.Flight_number as ThirdFlightNumber,f1.scheduled_departure_time as first_depart, f1.scheduled_arrival_time as arr1, f2.scheduled_departure_time as depart2,f2.scheduled_arrival_time as arrival_2, f3.scheduled_departure_time as depart3, f3.scheduled_arrival_time as origin_arrival_time, f1.weekdays as firstweekday, f2.weekdays as secondweekday, f3.weekdays as thirdweekday, f1.Departure_airport_code as Origin,f1.Arrival_airport_code as FirstStop, f2.Arrival_airport_code as SecondStop , f3.Arrival_airport_code as Destination from FLIGHT as f1 join FLIGHT as f2 join FLIGHT as f3 on (f1.Arrival_airport_code=f2.Departure_airport_code AND f2.Arrival_airport_code=f3.Departure_airport_code) and timediff(f2.Scheduled_Departure_time,f1.Scheduled_arrival_time)>='01:00:00' and timediff(f3.Scheduled_Departure_time,f2.Scheduled_arrival_time)>='01:00:00' where f1.Departure_airport_code='CLE' AND f3.Arrival_airport_code='DFW' and ((f1.Weekdays NOT like '%Mon%' or f2.Weekdays like '%Mon%') or (f1.Weekdays NOT like '%Tue%' or f2.Weekdays like '%Tue%') or (f1.Weekdays NOT like '%Wed%' or f2.Weekdays like '%Wed%') or (f1.Weekdays NOT like '%Thu%' or f2.Weekdays like '%Thu%') or (f1.Weekdays NOT like '%Fri%' or f2.Weekdays like '%Fri%') or (f1.Weekdays NOT like '%Sat%' or f2.Weekdays like '%Sat%') or (f1.Weekdays NOT like '%Sun%' or f2.Weekdays like '%Sun%')) and ((f2.Weekdays NOT like '%Mon%' or f3.Weekdays like '%Mon%') or (f2.Weekdays NOT like '%Tue%' or f3.Weekdays like '%Tue%') or (f2.Weekdays NOT like '%Wed%' or f3.Weekdays like '%Wed%') or (f2.Weekdays NOT like '%Thu%' or f3.Weekdays like '%Thu%') or (f2.Weekdays NOT like '%Fri%' or f3.Weekdays like '%Fri%') or (f2.Weekdays NOT like '%Sat%' or f3.Weekdays like '%Sat%') or (f2.Weekdays NOT like '%Sun%' or f3.Weekdays like '%Sun%'));




Select DISTINCT f1.Flight_number as FirstFlightNumber, f2.Flight_number as SecondFlightNumber, f1.weekdays as firstweekday, f2.weekdays as secondweekday,  f1.Departure_airport_code as Origin,f1.Arrival_airport_code as FirstStop, f2.Arrival_airport_code as Destination from FLIGHT as f1 join FLIGHT as f2 on (f1.Arrival_airport_code=f2.Departure_airport_code) and timediff(f2.Scheduled_Departure_time,f1.Scheduled_arrival_time)>='01:00:00' where f1.Departure_airport_code='DFW' AND f2.Arrival_airport_code='OAK' and ( (f1.Weekdays NOT like '%Mon%' or f2.Weekdays like '%Mon%') or (f1.Weekdays NOT like '%Tue%' or f2.Weekdays like '%Tue%') or (f1.Weekdays NOT like '%Wed%' or f2.Weekdays like '%Wed%') or (f1.Weekdays NOT like '%Thu%' or f2.Weekdays like '%Thu%') and (f1.Weekdays NOT like '%Fri%' or f2.Weekdays like '%Fri%') or (f1.Weekdays NOT like '%Sat%' or f2.Weekdays like '%Sat%') or (f1.Weekdays NOT like '%Sun%' or f2.Weekdays like '%Sun%'));